name: chooserbort
description: ChooserBort - App di conta
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/
